#!/usr/bin/env bash

set -eou pipefail

mkdir -p /tmp/nixtest
cp -R pkgs /tmp/nixtest
cp ./*.nix /tmp/nixtest
cp ./facebook-hosts /tmp/nixtest
touch /tmp/nixtest/extra-hosts

TMPDIR=/tmp/nixtest
TMPCONFIG="$TMPDIR/configuration.nix"
export NIXOS_CONFIG="$TMPCONFIG"

sed -e '/timesyncd/d' configuration.nix > "$TMPCONFIG"
echo '{}' > "$TMPDIR/hardware-configuration.nix"
echo '{ networking.hostId = "aaaaaaaa"; }' > "$TMPDIR/machine-configuration.nix"

nixos-rebuild build-vm
echo "Connect with 'ssh -p 2222 localhost'"
QEMU_NET_OPTS="hostfwd=tcp::2222-:22" ./result/bin/run-*-vm
